# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc19226c68500abbd12c198757e5943125d780fd5a7a6d73163d4af5e1280ab052caf9beec8c0ca277bfd386c3123490059b465bae17960ac37507ac982510cd

test:
  secret_key_base: d6dc2defce97e441488cca102502cc83ae211a51a1f5d222f69c286e532855ba59f525d12c014b0dc7e6b74eedc2745d286120d2a0994ef9cd0484e548bdffb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
